CREATE TABLE PRICES (
    PRICE_ID BIGINT,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    BRAND_ID VARCHAR(20) NOT NULL,
    PRICE_LIST VARCHAR(20) NOT NULL,
    START_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    END_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    PRICE DECIMAL(19, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    PRIORITY INT NOT NULL,
    PRIMARY KEY (PRICE_ID)
);